apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: ridego

  source:
    repoURL: https://github.com/orinameh/ridego
    targetRevision: main
    path: infra/k8s/services/user

  destination:
    server: https://kubernetes.default.svc
    namespace: ridego

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
